### ISSUE TITLE
maybe remove <li> from flash.each

### ISSUE THREAD

**Issue by thutterer** [thutterer/components#40]
... because it's never(?) more than one entry and looks weird.

**Comment by mschnitzer** [comment]
Nope. In some cases we have more than one entries.

**Comment by thutterer** [comment]
never saw one. maybe in 5% of all common cases. so 95% percent were wrong.
fixed with https://github.com/thutterer/components/commit/6b677d8ea353ade6ddda3a376ce1480e9c6ea038
if you don't like this change you can solve this more elegantly than me with an `if foo.count` condition.
